[package]
name = "WRO-goalkeeper-v002"
version = "0.1.0"
authors = ["janfe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ev3dev-lang-rust = "0.10.0"
